const UPDATE_APP_LIST = 'apps/UPDATE_APP_LIST'

const FETCH_APPS_STARTED = 'apps/FETCH_APPS_STARTED'
const FETCH_APPS_FINISHED = 'apps/FETCH_APPS_FINISHED'
const FETCH_APPS_ERROR = 'apps/FETCH_APPS_ERROR'

const UPDATE_INSTANCE_IDENTIFIER = 'apps/UPDATE_INSTANCE_IDENTIFIER'

export {
  UPDATE_APP_LIST,
  FETCH_APPS_STARTED,
  FETCH_APPS_FINISHED,
  FETCH_APPS_ERROR,
  UPDATE_INSTANCE_IDENTIFIER
}
