# Uncomment the next line to define a global platform for your project
platform :osx, '10.12'

target 'Blockstack' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Blockstack

  pod 'Sparkle'
  pod 'Swifter'

  target 'BlockstackTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BlockstackUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
