const requireHacker = require('require-hacker')
requireHacker.hook('png', () => 'module.exports = ""')
requireHacker.hook('svg', () => 'module.exports = ""')
requireHacker.hook('webp', () => 'module.exports = ""')
requireHacker.hook('css', () => 'module.exports = ""')
