export const PROFILE_UPLOADING = 'profiles/registration/PROFILE_UPLOADING'
export const PROFILE_UPLOAD_ERROR = 'profiles/registration/PROFILE_UPLOAD_ERROR'
export const REGISTRATION_SUBMITTING = 'profiles/registration/REGISTRATION_SUBMITTING'
export const REGISTRATION_SUBMITTED = 'profiles/registration/REGISTRATION_SUBMITTED'
export const REGISTRATION_ERROR = 'profiles/registration/REGISTRATION_ERROR'
export const REGISTRATION_BEFORE_SUBMIT = 'profiles/registration/REGISTRATION_BEFORE_SUBMIT'
